### ISSUE TITLE
Soft Deletes should be undone based on data found in events

### ISSUE THREAD

**Issue by Larry-Schultz** [Larry-Schultz/FFTB_Viewer#92]
Soft deleted accounts cannot have data added to them and throw a data integrity exception.  Need to add code to undo this across the board.

**Comment by OtherBrand** [comment]
This should be working now.  I don't see Data Integrity Exceptions being spammed in my logs.

**Comment by Larry-Schultz** [comment]
Still getting errors about soft deleted entries.  Re-opening this bug.

**Comment by Larry-Schultz** [comment]
Changing the behavior for now to just report which player is having the soft delete issues in discord.

This may be a non-issue, or the resolution may be something unexpected.

**Comment by Larry-Schultz** [comment]
New code change should be in prod for this.  Let's keep an eye on it.

**Comment by Larry-Schultz** [comment]
This work has been taken over by issue #127
